### ISSUE TITLE
Encountered an Error Running the Default Demo

### ISSUE THREAD

**Issue by yrf1** [AnyiRao/SceneSeg#24]
I got NoneType in the pairlist of `utilis/dataset_utilis.py`:
 ```
...visualize scene video in demo mode, the above quantitive metrics are invalid
Traceback (most recent call last):
  File "run.py", line 210, in <module>
    main()
  File "run.py", line 205, in main
    scene_dict, scene_list = pred2scene(cfg, threshold=0.8)
  File "/shared/nas/data/users/yifung/data/MovieNet/yi/data_preproc/SceneSeg/lgss/utilis/dataset_utilis.py", line 166, in pred2scene
    scene_list,pair_list = get_demo_scene_list(cfg,pred_list)
  File "/shared/nas/data/users/yifung/data/MovieNet/yi/data_preproc/SceneSeg/lgss/utilis/dataset_utilis.py", line 55, in get_demo_scene_list
    for pair in pair_list:
TypeError: 'NoneType' object is not iterable
```

Update: okay I read in previous closed issues that maybe the default demo video doesn't have multiple scenes to segment. Will try another video file and see.

**Comment by Bornedtobewilling** [comment]
> 

Hello, yrf1, I have encountered the same problem like yours. Have you solved it already?

**Comment by v-prgmr** [comment]
@Bornedtobewilling same here, I am trying to understand the shot_detect.py.
